version: "3.8"

services:
  example_system:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    ports:
      - "4000:4000"
      # Overrides default command so things don't shut down after the process ends.
    command: sh -c "cd workspace/example_system && mix deps.get && mix compile && cd assets && npm install && cd .. && mix phx.server"
